import re
from pathlib import Path


GLOB_PATTERN = "../lectures/*/images/*.svg"

IDENT_LINE = "<!-- Do not edit this file with editors other than draw.io -->"
PATTERN = r"(light-dark\(\s*)((?:[^(),]|\([^()]*\))+)(\s*,\s*)((?:[^(),]|\([^()]*\))+)(\s*\);?)"
REPLACEMENT = r"\g<1>\g<2>\g<3>\g<2>\g<5>" # Replaces group 4 (dark color) with group 2 (light color)


def get_all_svgs(pattern: str = GLOB_PATTERN) -> list[Path]:
    """Get all SVG files matching the glob pattern."""
    script_dir = Path(__file__).resolve().parent
    return list(script_dir.glob(pattern))


def has_ident_line(p: Path, ident_line: str) -> bool:
    """Check if the given file contains the specified identification line."""

    ident_line_stripped = ident_line.strip()

    with p.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip() == ident_line_stripped:
                return True

    return False


def replace_darkmode_color(svg_path: Path, search_regex: str, replace_regex: str) -> None:
    """Find occurrences of the search regex given SVG file and replace groups according to the replacement pattern."""

    search_re = re.compile(search_regex)

    text = svg_path.read_text(encoding="utf-8")
    new_text, num_subs = search_re.subn(replace_regex, text)

    if num_subs:
        #print(f"  Replaced {num_subs} occurrence(s) in {svg_path.name}")

        svg_path.write_text(new_text, encoding="utf-8")


if __name__ == "__main__":

    for file_path in get_all_svgs():
        if has_ident_line(file_path, IDENT_LINE): 
            replace_darkmode_color(file_path, PATTERN, REPLACEMENT)